# Peripheral (right) half OLED settings

# WPM tracking not available on peripheral
CONFIG_ZMK_WPM=n

# Disable signal/output indicator
CONFIG_NICE_OLED_WIDGET_OUTPUT_BACKGROUND=n

# Battery (enabled by default)

# Pokemon animation
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
