# Central (left) half OLED settings

# Luna animation (responds to typing)
CONFIG_ZMK_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=y
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=n

# Modifiers with macOS symbols
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_MACOS=y

# Layer indicator
CONFIG_NICE_OLED_WIDGET_LAYER=y
